# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=10)),
                ('s_school', models.CharField(max_length=10)),
                ('s_create_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
